# Generated by Django 4.1.1 on 2022-09-26 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('mainapp', '0002_document_number_check_document_work_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('document', models.FileField(upload_to=mainapp.models.get_path, validators=[django.core.validators.FileExtensionValidator(['docx'])], verbose_name='Файл')),
                ('work_shift', models.CharField(choices=[('д', 'Дневная'), ('н', 'Ночная')], default='д', max_length=1, verbose_name='Рабочая смена')),
                ('number_check', models.CharField(default='ABC123', max_length=50, verbose_name='Номер предписания')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
